### ISSUE TITLE
Upload.sh fails: 'curl: option --form: is badly used here'

### ISSUE THREAD

**Issue by thomwiggers** [squell/bb-scripts#52]
```
./upload.sh grades.csv
Still logged in!
curl: option --form: is badly used here
curl: try 'curl --help' or 'curl --manual' for more information
Please set the BlackBoard interface language to English.
```

**Comment by camilstaps** [comment]
Is this the same as #49?

**Comment by thomwiggers** [comment]
It still happened for me on a fresh clone, and for the OO course going by reports from @pingiun

**Comment by squell** [comment]
Presumable, this is because `$NONCE` is empty in this script; this might be because the URL `$BBUPLOAD` is invalid, or the filter function `nonce()` that extracts  it misses it because of some changes to the HTML structure. However, I cannot reproduce it!

@thomwiggers, can you edit upload.sh so that it does `$CURL "$BBUPLOAD" > barf` right before it fetches the nonce, and then send it to me by mail? (Unless of course you already see that it says something like "Error, you are not logged in", in which case the problems occurs earlier)

**Comment by thomwiggers** [comment]
I'm able to fix it by fixing the BBCOURSEID, as it's still duplicated.

**Comment by squell** [comment]
That helps! The last "fix" in commit 4fe55c98192d09fc535fa327c9867a153f2dc1d1 also alters the line in `verdeel.sh` that alters (don't you hate double indirection) the line in `upload.sh` that is sent to the TA's. 

Patched by 8de70fdf73fac0dd3d65c5c0cb53fe0715f7c9be. If that works for you, this can be closed.

**Comment by squell** [comment]
Note: if anybody is bothered by this on a wizard-configurated setup, change line 104 in `verdeel.sh` back to `BBCOURSEID=$BBCOURSEID`.

**Comment by thomwiggers** [comment]
Appears to have worked.
