### ISSUE TITLE
Running into errors.

### ISSUE THREAD

**Issue by W-M-T** [squell/bb-scripts#54]
I'm currently running into a bunch of errors during the new workflow.

One that I get is the following (sensitive data replaced):
```sh
tar: Cannot connect to no1-6203 - name1 - date1: resolve failed
tar: Cannot connect to no2-6203 - name2 - date2: resolve failed
```
These are the students which have .tar.gz archives as their submission.
Later in the execution of ```verdeel.sh``` it crashes with the line:
```sh
./verdeel.sh: line 128: test: too many arguments
```

When I unzip the zip and manually replace those archives by their .zip versions, the scripts do run to the end. There are still other errors though.
These are of this form:
```sh
could not find entry for student: Dani/ Dani/,Dani/
could not find entry for student: #s999999
could not find entry for student: #s999998
could not find entry for student: #s999998
could not find entry for student: #s999999
```
I suspect that the first case in here has to do with a student named Daniël, and something with the mojibake goes wrong, but I'm still surprised to see names in a list of (mostly repeated) unfound s-nrs.

**Comment by squell** [comment]
Sounds like an unquoted filename is being handled somewhere. The .tar.gz part of antifmt.sh is poorly tested anyway since not many students (in the courses that I've seen) submit in that format.

I think the warnings about 999999 are probably because that number is in a file submitted by a student? It is normal that both names and studentnumbers can show up in that list: identify.sh first looks up the name-part from the directory name (which in this case probably gets clipped because you didn't unmoji-bake it), then any possible studentnumbers found in submitted files. So those warnings are, I think, identify.sh doing exactly what it should: complain about things that are strange.

**Comment by W-M-T** [comment]
The unmojibaking happens in bsunzip.sh right? I didn't change any of the code there, and I also didn't get any ```iconv``` error.
I think it has to do with the way that the student directories are created.
If I have a student named Daniël, the scripts create a student directory for them named "Dani" (with the rest, including submission date, cut off).
This behaviour differs from normal unzipping behaviour, because that keeps the diacritics in folder names intact.

**Comment by squell** [comment]
Ah, I understood you to mean that you unzipped it by hand. Are you running it on lilo5/lilo6 or your own machine? And what is the environment variable `LC_CTYPE` set to?

**Comment by squell** [comment]
What does `locale`  say?

**Comment by squell** [comment]
In the mean time, I discovered that for some reason, if you unzip the Brightspace .zip when running under the POSIX locale (using plain unzip), it creates directory names without mojibake. Weird.

**Comment by squell** [comment]
Ah, that is because in POSIX, unzip's unicode support is disabled, and it won't try to recode the filenames. So I can simplify things there. Nice.

**Comment by squell** [comment]
Also, `tar` seems to be stumped by the `:` in the folder names.

**Comment by W-M-T** [comment]
I don't know whether this info is still relevant, but ```locale``` produces the following output on lilo5:
```
LANGUAGE=en_US:
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=
```

**Comment by W-M-T** [comment]
I've sent you the names on your science mail, but it seems that that specific error was also fixed by fixing the unzipping process, when trying to reproduce it using the updated scripts.
I do get a new error now:
```tar: %{file%/*}: Cannot open: No such file or directory```

**Comment by squell** [comment]
Well, that is obviously because one does not start variables in bash with %...  :flushed: 

I think the errors were caused because the directory names were clipped; the fixes introduced earlier should take care of that. Probably nicer to give a more distinct error message about that, which is something I will type up on monday. Thanks for the debugging run!

**Comment by dopefishh** [comment]
I encounter similar problems with surname Könings (K+nings when printed with garble)

**Comment by squell** [comment]
@dopefishh Could you send the ZIP that caused that?

**Comment by squell** [comment]
Sadly, that one is a "works for me" wit the latest version; of course I don't have that student in my .csv file, but it does try to identify that student:

```
$ ./bsunzip.sh Submission*.piz
$ ./identify.sh students.csv *Könings*/
could not find entry for student: Könings,Xxxxxx
```

**Comment by dopefishh** [comment]
Good, that means it is my system. I'll investigate...

**Comment by squell** [comment]
This issue is closed by #61, right?

**Comment by dopefishh** [comment]
For me, yes

**Comment by W-M-T** [comment]
Sorry for the late reply, but yes this issue seems fixed.
